### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by timuxi** [bducgroup/DeepGPS#1]
<\DeepGPS-main> python Predict.py
len: 7
model_path ./trained_model.pkl
Traceback (most recent call last):
  File "Predict.py", line 22, in <module>
    checkpoint = torch.load(model_path)
  File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by timuxi** [comment]
```
$ git-lfs clone https://github.com/bducgroup/DeepGPS.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'DeepGPS'...
remote: Enumerating objects: 225, done.
remote: Counting objects: 100% (225/225), done.
remote: Compressing objects: 100% (208/208), done.
Receremote: Total 225 (delta 15), reused 222 (delta 15), pack-reused 0
Receiving objects: 100% (225/225), 373.09 KiB | 1.14 MiB/s, done.
Resolving deltas: 100% (15/15), done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/bducgroup/DeepGPS.git/info/lfs'
```

**Comment by timuxi** [comment]
![image](https://user-images.githubusercontent.com/78781986/199439794-aed2f77f-fb78-4762-aebb-fff63e521cbf.png)

**Comment by zhantt626** [comment]
> <\DeepGPS-main> python Predict.py len: 7 model_path ./trained_model.pkl Traceback (most recent call last): File "Predict.py", line 22, in checkpoint = torch.load(model_path) File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 593, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 762, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.



> ```
> $ git-lfs clone https://github.com/bducgroup/DeepGPS.git
> WARNING: 'git lfs clone' is deprecated and will not be updated
>           with new flags from 'git clone'
> 
> 'git clone' has been updated in upstream Git to have comparable
> speeds to 'git lfs clone'.
> Cloning into 'DeepGPS'...
> remote: Enumerating objects: 225, done.
> remote: Counting objects: 100% (225/225), done.
> remote: Compressing objects: 100% (208/208), done.
> Receremote: Total 225 (delta 15), reused 222 (delta 15), pack-reused 0
> Receiving objects: 100% (225/225), 373.09 KiB | 1.14 MiB/s, done.
> Resolving deltas: 100% (15/15), done.
> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> error: failed to fetch some objects from 'https://github.com/bducgroup/DeepGPS.git/info/lfs'
> ```

Hello,
      I would like to ask you how you finally solved this problem, because I also encountered this problem recently. Looking forward to your reply! Thank you very much.

**Comment by timuxi** [comment]
> > <\DeepGPS-main> python Predict.py len: 7 model_path ./trained_model.pkl Traceback (most recent call last): File "Predict.py", line 22, in checkpoint = torch.load(model_path) File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 593, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 762, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.
> 
> > ```
> > $ git-lfs clone https://github.com/bducgroup/DeepGPS.git
> > WARNING: 'git lfs clone' is deprecated and will not be updated
> >           with new flags from 'git clone'
> > 
> > 'git clone' has been updated in upstream Git to have comparable
> > speeds to 'git lfs clone'.
> > Cloning into 'DeepGPS'...
> > remote: Enumerating objects: 225, done.
> > remote: Counting objects: 100% (225/225), done.
> > remote: Compressing objects: 100% (208/208), done.
> > Receremote: Total 225 (delta 15), reused 222 (delta 15), pack-reused 0
> > Receiving objects: 100% (225/225), 373.09 KiB | 1.14 MiB/s, done.
> > Resolving deltas: 100% (15/15), done.
> > batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> > error: failed to fetch some objects from 'https://github.com/bducgroup/DeepGPS.git/info/lfs'
> > ```
> 
> Hello, I would like to ask you how you finally solved this problem, because I also encountered this problem recently. Looking forward to your reply! Thank you very much.

i contact with author by email , and he give me the model. u can try to contact by email, it seems he does not look over the issues

**Comment by zhantt626** [comment]
> > > <\DeepGPS-main> python Predict.py len: 7 model_path ./trained_model.pkl Traceback (most recent call last): File "Predict.py", line 22, in checkpoint = torch.load(model_path) File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 593, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "C:\Users\35381\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 762, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'v'.
> > 
> > 
> > > ```
> > > $ git-lfs clone https://github.com/bducgroup/DeepGPS.git
> > > WARNING: 'git lfs clone' is deprecated and will not be updated
> > >           with new flags from 'git clone'
> > > 
> > > 'git clone' has been updated in upstream Git to have comparable
> > > speeds to 'git lfs clone'.
> > > Cloning into 'DeepGPS'...
> > > remote: Enumerating objects: 225, done.
> > > remote: Counting objects: 100% (225/225), done.
> > > remote: Compressing objects: 100% (208/208), done.
> > > Receremote: Total 225 (delta 15), reused 222 (delta 15), pack-reused 0
> > > Receiving objects: 100% (225/225), 373.09 KiB | 1.14 MiB/s, done.
> > > Resolving deltas: 100% (15/15), done.
> > > batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> > > error: failed to fetch some objects from 'https://github.com/bducgroup/DeepGPS.git/info/lfs'
> > > ```
> > 
> > 
> > Hello, I would like to ask you how you finally solved this problem, because I also encountered this problem recently. Looking forward to your reply! Thank you very much.
> 
> i contact with author by email , and he give me the model. u can try to contact by email, it seems he does not look over the issues

Got it! Thanks for your reply and everything goes well for you！
